"""Generate the manuscript's LaTeX tables from the analysis outputs.

Tables are GENERATED, never hand-typed: a number transcribed by hand is a number that
silently goes stale when the analysis is re-run. Every value here is read from the same
CSVs the figures use, so `python make_tables.py` after a re-run keeps the paper honest.

    python make_tables.py            # write all tables to tables/
    python make_tables.py --print    # also echo them to stdout

Output is booktabs + siunitx. Add to the preamble:
    \\usepackage{booktabs}
    \\usepackage{siunitx}
    \\usepackage{multirow}
"""
from __future__ import annotations

import argparse
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..")
AGREE = os.path.join(REPO, "data_evaluation", "vlm_judge", "agreement_output")
# tables/ is generated output and is gitignored, like figures/ beside it.
TABLE_DIR = os.path.join(HERE, "tables")

# (benchmark, criterion in the distribution file, criterion key in the Mann-Whitney file,
#  row label for the table)
PILLAR1_ROWS = [
    (1, "Knowledge Interpretation/Deduction",
     "OE_correct_KnowledgeInterpretation", "B1 Knowledge interpretation"),
    (1, "Visual Grounding",
     "OE_correct_VisualGrounding", "B1 Visual grounding"),
    (3, "Visual Grounding/Reasoning",
     "CE_correct_VisualGrounding", "B3 Visual grounding"),
]


def _load():
    scores = pd.read_csv(os.path.join(AGREE, "evaluator_score_distributions.csv"))
    homogeneity = pd.read_csv(os.path.join(AGREE, "evaluator_homogeneity_tests.csv"))
    mann_whitney = pd.read_csv(os.path.join(AGREE, "pathopen_vs_pathvqa_mannwhitney.csv"))
    return scores, homogeneity, mann_whitney


def table1_dataset_quality() -> str:
    """Main-text table: the headline Pillar 1 comparison."""
    scores, homogeneity, mann_whitney = _load()
    human = mann_whitney[mann_whitney.rater == "human"].set_index("criterion")

    lines = [
        r"% Generated by tables/make_tables.py - do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{\textbf{PathOPEN item quality against filtered PathVQA.} "
        r"Scores are on the ordinal scale $\{-1,0,1,2\}$, where $-1$ marks an item a "
        r"pathologist could not evaluate. Mean and effect size pool the five "
        r"pathologists; \% max, \% unscorable and rater spread are computed per "
        r"pathologist and then averaged, so the mean and \% max columns need not move "
        r"together. Effect size is the rank-biserial correlation with a bootstrapped "
        r"95\% CI (2{,}000 resamples); negative values indicate PathOPEN ranks higher. "
        r"Rater spread is the range of the five pathologists' mean scores -- smaller is "
        r"more consistent.}",
        r"\label{tab:dataset-quality}",
        r"\sisetup{table-format=-1.3}",
        r"\begin{tabular}{l"
        r" S[table-format=1.2] S[table-format=1.2]"
        r" S[table-format=2.1] S[table-format=2.1]"
        r" S[table-format=2.1] S[table-format=2.1]"
        r" S[table-format=1.2] S[table-format=1.2]"
        r" c}",
        r"\toprule",
        r" & \multicolumn{2}{c}{Mean score} & \multicolumn{2}{c}{\% max score}"
        r" & \multicolumn{2}{c}{\% unscorable} & \multicolumn{2}{c}{Rater spread}"
        r" & {Effect size} \\",
        r"\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7} \cmidrule(lr){8-9}",
        r"Criterion & {PathOPEN} & {PathVQA} & {PathOPEN} & {PathVQA}"
        r" & {PathOPEN} & {PathVQA} & {PathOPEN} & {PathVQA} & {[95\% CI]} \\",
        r"\midrule",
    ]

    for benchmark, criterion, effect_key, label in PILLAR1_ROWS:
        cells = {}
        for source, key in (("PathOPEN", "po"), ("Filtered_PathVQA", "pv")):
            subset = scores[(scores.dataset == source)
                            & (scores.benchmark == benchmark)
                            & (scores.criterion == criterion)]
            cells[key] = {
                "pct_max": subset.pct_2.mean(),
                "pct_defect": subset["pct_-1"].mean(),
                "spread": subset["mean"].max() - subset["mean"].min(),
            }
        row = human.loc[effect_key]
        significant = row.rb_ci_high < 0
        effect = (f"{row.rank_biserial:.3f} "
                  f"[{row.rb_ci_low:.2f}, {row.rb_ci_high:.2f}]")
        lines.append(
            f"{label} & {row.mean_pathopen:.2f} & {row.mean_pathvqa:.2f} & "
            f"{cells['po']['pct_max']:.1f} & {cells['pv']['pct_max']:.1f} & "
            f"{cells['po']['pct_defect']:.1f} & {cells['pv']['pct_defect']:.1f} & "
            f"{cells['po']['spread']:.2f} & {cells['pv']['spread']:.2f} & "
            f"{effect} \\\\")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def table_s1_per_evaluator() -> str:
    """Supplementary: the full per-pathologist score distribution."""
    scores, homogeneity, _ = _load()
    subset = scores[scores.dataset.isin(["PathOPEN", "Filtered_PathVQA"])
                    & scores.benchmark.isin([1, 3])]

    lines = [
        r"% Generated by tables/make_tables.py - do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{\textbf{Per-pathologist score distributions.} Each item was rated by "
        r"exactly one pathologist, so no per-item agreement statistic (Fleiss' $\kappa$, "
        r"Krippendorff's $\alpha$) is computable; what can be tested is whether the five "
        r"raters' score \emph{distributions} differ across the pools each of them saw. "
        r"$P$ is from a Kruskal--Wallis test across the five raters. PathOPEN's raters "
        r"differ far less than filtered PathVQA's, and on Benchmark 3 they are "
        r"statistically indistinguishable. Note that PathOPEN's narrow spread is partly "
        r"a ceiling effect: when 90--99\% of scores are the maximum there is little room "
        r"to disagree.}",
        r"\label{tab:per-evaluator}",
        r"\begin{tabular}{l l S[table-format=4.0]"
        r" S[table-format=1.3] S[table-format=1.3] S[table-format=1.3]"
        r" S[table-format=1.3] S[table-format=1.3]"
        r" S[table-format=1.2] c}",
        r"\toprule",
        r"Dataset & Criterion & {$n$} & \multicolumn{5}{c}{Pathologist mean score}"
        r" & {Spread} & {$P$} \\",
        r"\cmidrule(lr){4-8}",
        r" & & & {P1} & {P2} & {P3} & {P4} & {P5} & & \\",
        r"\midrule",
    ]

    display = {"PathOPEN": "PathOPEN", "Filtered_PathVQA": "filtered PathVQA"}
    for source in ("PathOPEN", "Filtered_PathVQA"):
        for benchmark, criterion, _, label in PILLAR1_ROWS:
            rows = subset[(subset.dataset == source)
                          & (subset.benchmark == benchmark)
                          & (subset.criterion == criterion)].sort_values("evaluator")
            if rows.empty:
                continue
            test = homogeneity[(homogeneity.dataset == source)
                               & (homogeneity.benchmark == benchmark)
                               & (homogeneity.criterion == criterion)]
            p_value = test.kruskal_p.iloc[0] if not test.empty else float("nan")
            p_text = (r"\textbf{n.s.}" if p_value >= 0.05
                      else (r"$<$0.001" if p_value < 0.001 else f"{p_value:.3f}"))
            means = " & ".join(f"{v:.3f}" for v in rows["mean"])
            spread = rows["mean"].max() - rows["mean"].min()
            lines.append(f"{display[source]} & {label} & {int(rows.n.sum())} & {means}"
                         f" & {spread:.2f} & {p_text} \\\\")
        if source == "PathOPEN":
            lines.append(r"\midrule")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def table_s2_defect_mechanism() -> str:
    """Supplementary: per-rater unscorable rates.

    Stronger than the mean-score comparison, because raters disagreeing about whether an
    item can be evaluated AT ALL is a more fundamental defect than disagreeing about its
    quality."""
    scores, _, _ = _load()
    subset = scores[scores.dataset.isin(["PathOPEN", "Filtered_PathVQA"])
                    & scores.benchmark.isin([1, 3])]

    lines = [
        r"% Generated by tables/make_tables.py - do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{\textbf{Per-pathologist rate of unscorable items.} Percentage of items "
        r"each pathologist scored $-1$ (``unable to comprehend the question and/or image, "
        r"or unable to make the evaluation''). On PathOPEN four of the five raters marked "
        r"\emph{no} item unscorable on any criterion, and the widest disagreement between "
        r"raters is 3.6 percentage points. On filtered PathVQA the same five raters "
        r"disagree by up to 70 points about whether items can be evaluated at all -- on "
        r"Benchmark 3 one pathologist found every item scorable while another rejected "
        r"70\% of theirs. Disagreement about answerability is a more fundamental defect "
        r"than disagreement about quality, because it means the item does not present a "
        r"well-posed question.}",
        r"\label{tab:defect-mechanism}",
        r"\begin{tabular}{l l S[table-format=2.1] S[table-format=2.1] S[table-format=2.1]"
        r" S[table-format=2.1] S[table-format=2.1] S[table-format=2.1] S[table-format=3.0]}",
        r"\toprule",
        r"Dataset & Criterion & \multicolumn{5}{c}{\% items scored $-1$, per pathologist}"
        r" & {Range} & {Pooled} \\",
        r"\cmidrule(lr){3-7}",
        r" & & {P1} & {P2} & {P3} & {P4} & {P5} & & {$n_{-1}$} \\",
        r"\midrule",
    ]

    display = {"PathOPEN": "PathOPEN", "Filtered_PathVQA": "filtered PathVQA"}
    for source in ("PathOPEN", "Filtered_PathVQA"):
        for benchmark, criterion, _, label in PILLAR1_ROWS:
            rows = subset[(subset.dataset == source)
                          & (subset.benchmark == benchmark)
                          & (subset.criterion == criterion)].sort_values("evaluator")
            if rows.empty:
                continue
            rates = " & ".join(f"{v:.1f}" for v in rows["pct_-1"])
            spread = rows["pct_-1"].max() - rows["pct_-1"].min()
            total = int(rows["n_-1"].sum())
            lines.append(f"{display[source]} & {label} & {rates} & {spread:.1f}"
                         f" & {total} \\\\")
        if source == "PathOPEN":
            lines.append(r"\midrule")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


# --- Pillar 2 -------------------------------------------------------------------------

HUMAN_INPUT = os.path.join(REPO, "data_evaluation", "pathologists",
                           "scoring_analysis", "input")
JUDGE_OUTPUT = os.path.join(REPO, "data_evaluation", "vlm_judge", "judge_output")

# score 2 -> near-miss, 1 -> moderate-miss, 0 -> far-miss, -1 -> excluded (no tier).
# Same binning as wrong_answer_tier_agreement.ipynb.
TIER_ORDER = ["near-miss", "moderate-miss", "far-miss"]
_WRONG_COLUMNS = ([f"Evaluation OE_Wrong_Answer_{i}\n(Benchmark 2)" for i in (1, 2)]
                  + [f"Evaluation MCQ_OE_Wrong_Answer_{i}\n(Benchmark 2)"
                     for i in (1, 2, 3, 4)])


def _pooled_human():
    import glob
    frames = []
    directories = sorted(glob.glob(os.path.join(HUMAN_INPUT, "evaluator[0-9]*")),
                         key=lambda p: int(os.path.basename(p).replace("evaluator", "")))
    for directory in directories:
        path = os.path.join(directory, "pathopen_eval_data.csv")
        if os.path.exists(path):
            # Row 0 is a second header line in these exports.
            frames.append(pd.read_csv(path).drop(index=0).reset_index(drop=True))
    return pd.concat(frames, ignore_index=True)


def _confusion(judge_key):
    """3x3 counts, rows = pathologist tier, columns = judge tier."""
    import numpy as np
    human = _pooled_human()
    judge = pd.read_csv(os.path.join(JUDGE_OUTPUT, f"evaluator_{judge_key}",
                                     "pathopen_eval_data.csv"))
    merged = human.merge(judge, on="Image_ID", suffixes=("_human", "_judge"))
    matrix = np.zeros((3, 3), dtype=int)
    index_of = {2: 0, 1: 1, 0: 2}
    for column in _WRONG_COLUMNS:
        h = pd.to_numeric(merged.get(f"{column}_human", merged.get(column)),
                          errors="coerce")
        j = pd.to_numeric(merged.get(f"{column}_judge", merged.get(column)),
                          errors="coerce")
        for human_value, judge_value in zip(h, j):
            if human_value in index_of and judge_value in index_of:
                matrix[index_of[human_value], index_of[judge_value]] += 1
    return matrix


def table_s3_judge_calibration() -> str:
    """Supplementary: WHY the judges fail to reproduce the tiering.

    Reporting kappa alone says the agreement is poor; it does not say how. The marginals
    show the failure has a specific shape - both judges apply a systematically more
    generous plausibility threshold, inflating near-miss - which is diagnosable and
    potentially correctable, and is a more useful finding than a low kappa."""
    import numpy as np
    agreement = pd.read_csv(os.path.join(AGREE, "wrong_answer_tier_agreement.csv"))

    lines = [
        r"% Generated by make_tables.py - do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{\textbf{Why VLM judges do not reproduce the pathologists' difficulty "
        r"tiers.} Both judges assign the tiers with a systematically more generous "
        r"threshold rather than at random: each inflates the near-miss category "
        r"$2.4$--$3.0\times$ relative to the pathologists, and InternVL assigns far-miss to "
        r"only $14.2\%$ of items against the pathologists' $50.5\%$. Per-tier recall shows "
        r"the consequence -- InternVL calls an item near-miss $52.7\%$ of the time when the "
        r"pathologist did, but also $51.1\%$ of the time when the pathologist said "
        r"moderate-miss, so its assignment is close to independent of theirs. Agreement is "
        r"markedly worse on OE-native distractors, which are free text, than on MCQ-derived "
        r"ones, which are written as formatted options -- $2.7\times$ for InternVL and "
        r"$1.5\times$ for Qwen -- so the automation gap is widest exactly where the "
        r"distractor is not already option-shaped. This is a calibration failure, not "
        r"noise, and it is what makes Benchmark~2 unsuitable for automation in its "
        r"present form.}",
        r"\label{tab:judge-calibration}",
        r"\begin{tabular}{l l S[table-format=2.1] S[table-format=2.1] S[table-format=2.1]"
        r" S[table-format=1.2]}",
        r"\toprule",
        r" & & \multicolumn{3}{c}{Tier assigned (\%)} & {Near-miss} \\",
        r"\cmidrule(lr){3-5}",
        r"Rater & Split & {Near} & {Moderate} & {Far} & {inflation} \\",
        r"\midrule",
    ]

    matrices = {key: _confusion(key) for key in ("internvl", "qwenvl")}
    reference = matrices["internvl"]
    human_marginal = [100 * reference[i, :].sum() / reference.sum() for i in range(3)]
    lines.append("Pathologists & all & "
                 + " & ".join(f"{v:.1f}" for v in human_marginal) + r" & {--} \\")
    display = {"internvl": "InternVL judge", "qwenvl": "Qwen judge"}
    for key, matrix in matrices.items():
        judge_marginal = [100 * matrix[:, j].sum() / matrix.sum() for j in range(3)]
        inflation = judge_marginal[0] / human_marginal[0]
        lines.append(f"{display[key]} & all & "
                     + " & ".join(f"{v:.1f}" for v in judge_marginal)
                     + f" & {inflation:.2f} \\\\")

    lines += [
        r"\midrule",
        r"\multicolumn{6}{l}{\emph{Per-tier recall: what the judge said, given what the "
        r"pathologist said}} \\",
        r"\midrule",
    ]
    for key, matrix in matrices.items():
        for i, tier in enumerate(TIER_ORDER):
            total = matrix[i, :].sum()
            recall = [100 * matrix[i, j] / total for j in range(3)]
            lines.append(f"{display[key]} & path.\\ said {tier} & "
                         + " & ".join(f"{v:.1f}" for v in recall) + r" & {--} \\")

    # Weighted kappa by distractor source. This is the finding that judges do 2-3x worse
    # on free-text distractors, so it is a visible row block, not a footnote. The three
    # numeric columns are re-labelled for this block via a spanning subheader, because
    # mean/min/max are not tier percentages and must not sit under those headings.
    lines += [
        r"\midrule",
        r"\multicolumn{6}{l}{\emph{Weighted $\kappa$ against the pathologists, by source of "
        r"the distractor}} \\",
        r"\cmidrule(lr){3-5}",
        r" & & {Mean} & {Min} & {Max} & {Cells} \\",
        r"\midrule",
    ]
    for key in ("internvl", "qwenvl"):
        for source, label in (("OE_native", "OE-native (free text)"),
                              ("MCQ_derived", "MCQ-derived (option)")):
            rows = agreement[(agreement.judge == key) & (agreement.source == source)]
            lines.append(f"{display[key]} & {label} & "
                         f"{rows.weighted_kappa.mean():.3f} & "
                         f"{rows.weighted_kappa.min():.3f} & "
                         f"{rows.weighted_kappa.max():.3f} & "
                         f"{{{len(rows)}}} \\\\")

    # The ratio is the point of the block; state it rather than leaving it to be divided.
    ratios = []
    for key in ("internvl", "qwenvl"):
        oe = agreement[(agreement.judge == key)
                       & (agreement.source == "OE_native")].weighted_kappa.mean()
        mcq = agreement[(agreement.judge == key)
                        & (agreement.source == "MCQ_derived")].weighted_kappa.mean()
        ratios.append(f"{display[key]} ${mcq / oe:.1f}\\times$")

    lines += [r"\bottomrule", r"\end{tabular}",
              r"\begin{flushleft}\footnotesize Agreement is markedly worse on OE-native "
              r"distractors, which are free text, than on MCQ-derived ones, which are "
              r"written as formatted options ("
              + "; ".join(ratios) + r" higher $\kappa$ on MCQ-derived). Mean, min and max "
              r"are taken across that judge's criteria and distractor slots."
              r"\end{flushleft}",
              r"\end{table}", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", dest="echo", action="store_true")
    args = parser.parse_args()

    outputs = {
        "table1_dataset_quality.tex": table1_dataset_quality(),
        "tableS1_per_evaluator.tex": table_s1_per_evaluator(),
        "tableS2_defect_mechanism.tex": table_s2_defect_mechanism(),
        "tableS3_judge_calibration.tex": table_s3_judge_calibration(),
    }
    os.makedirs(TABLE_DIR, exist_ok=True)
    for name, content in outputs.items():
        path = os.path.join(TABLE_DIR, name)
        with open(path, "w") as f:
            f.write(content)
        print(f"wrote {name} ({len(content.splitlines())} lines)")
        if args.echo:
            print(content)


if __name__ == "__main__":
    main()
