"""Generate the manuscript's LaTeX tables from the analysis outputs.

Tables are GENERATED, never hand-typed: a number transcribed by hand is a number that
silently goes stale when the analysis is re-run. Every value here is read from the same
CSVs the figures use, so `python make_tables.py` after a re-run keeps the paper honest.

    python make_tables.py            # write all tables to tables/
    python make_tables.py --print    # also echo them to stdout

Output is booktabs + siunitx. Add to the preamble:
    \\usepackage{booktabs}
    \\usepackage{siunitx}
    \\usepackage{multirow}
"""
from __future__ import annotations

import argparse
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..")
AGREE = os.path.join(REPO, "data_evaluation", "vlm_judge", "agreement_output")
# tables/ is generated output and is gitignored, like figures/ beside it.
TABLE_DIR = os.path.join(HERE, "tables")

# (benchmark, criterion in the distribution file, criterion key in the Mann-Whitney file,
#  row label for the table)
PILLAR1_ROWS = [
    (1, "Knowledge Interpretation/Deduction",
     "OE_correct_KnowledgeInterpretation", "B1 Knowledge interpretation"),
    (1, "Visual Grounding",
     "OE_correct_VisualGrounding", "B1 Visual grounding"),
    (3, "Visual Grounding/Reasoning",
     "CE_correct_VisualGrounding", "B3 Visual grounding"),
]


def _load():
    scores = pd.read_csv(os.path.join(AGREE, "evaluator_score_distributions.csv"))
    homogeneity = pd.read_csv(os.path.join(AGREE, "evaluator_homogeneity_tests.csv"))
    mann_whitney = pd.read_csv(os.path.join(AGREE, "pathopen_vs_pathvqa_mannwhitney.csv"))
    return scores, homogeneity, mann_whitney


def table1_dataset_quality() -> str:
    """Main-text table: the headline Pillar 1 comparison."""
    scores, homogeneity, mann_whitney = _load()
    human = mann_whitney[mann_whitney.rater == "human"].set_index("criterion")

    lines = [
        r"% Generated by tables/make_tables.py - do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{\textbf{PathOPEN item quality against filtered PathVQA.} "
        r"Scores are on the ordinal scale $\{-1,0,1,2\}$, where $-1$ marks an item a "
        r"pathologist could not evaluate. Mean and effect size pool the five "
        r"pathologists; \% max, \% unscorable and rater spread are computed per "
        r"pathologist and then averaged, so the mean and \% max columns need not move "
        r"together. Effect size is the rank-biserial correlation with a bootstrapped "
        r"95\% CI (2{,}000 resamples); negative values indicate PathOPEN ranks higher. "
        r"Rater spread is the range of the five pathologists' mean scores -- smaller is "
        r"more consistent.}",
        r"\label{tab:dataset-quality}",
        r"\sisetup{table-format=-1.3}",
        r"\begin{tabular}{l"
        r" S[table-format=1.2] S[table-format=1.2]"
        r" S[table-format=2.1] S[table-format=2.1]"
        r" S[table-format=2.1] S[table-format=2.1]"
        r" S[table-format=1.2] S[table-format=1.2]"
        r" c}",
        r"\toprule",
        r" & \multicolumn{2}{c}{Mean score} & \multicolumn{2}{c}{\% max score}"
        r" & \multicolumn{2}{c}{\% unscorable} & \multicolumn{2}{c}{Rater spread}"
        r" & {Effect size} \\",
        r"\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7} \cmidrule(lr){8-9}",
        r"Criterion & {PathOPEN} & {PathVQA} & {PathOPEN} & {PathVQA}"
        r" & {PathOPEN} & {PathVQA} & {PathOPEN} & {PathVQA} & {[95\% CI]} \\",
        r"\midrule",
    ]

    for benchmark, criterion, effect_key, label in PILLAR1_ROWS:
        cells = {}
        for source, key in (("PathOPEN", "po"), ("Filtered_PathVQA", "pv")):
            subset = scores[(scores.dataset == source)
                            & (scores.benchmark == benchmark)
                            & (scores.criterion == criterion)]
            cells[key] = {
                "pct_max": subset.pct_2.mean(),
                "pct_defect": subset["pct_-1"].mean(),
                "spread": subset["mean"].max() - subset["mean"].min(),
            }
        row = human.loc[effect_key]
        significant = row.rb_ci_high < 0
        effect = (f"{row.rank_biserial:.3f} "
                  f"[{row.rb_ci_low:.2f}, {row.rb_ci_high:.2f}]")
        lines.append(
            f"{label} & {row.mean_pathopen:.2f} & {row.mean_pathvqa:.2f} & "
            f"{cells['po']['pct_max']:.1f} & {cells['pv']['pct_max']:.1f} & "
            f"{cells['po']['pct_defect']:.1f} & {cells['pv']['pct_defect']:.1f} & "
            f"{cells['po']['spread']:.2f} & {cells['pv']['spread']:.2f} & "
            f"{effect} \\\\")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def table_s1_per_evaluator() -> str:
    """Supplementary: the full per-pathologist score distribution."""
    scores, homogeneity, _ = _load()
    subset = scores[scores.dataset.isin(["PathOPEN", "Filtered_PathVQA"])
                    & scores.benchmark.isin([1, 3])]

    lines = [
        r"% Generated by tables/make_tables.py - do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{\textbf{Per-pathologist score distributions.} Each item was rated by "
        r"exactly one pathologist, so no per-item agreement statistic (Fleiss' $\kappa$, "
        r"Krippendorff's $\alpha$) is computable; what can be tested is whether the five "
        r"raters' score \emph{distributions} differ across the pools each of them saw. "
        r"$P$ is from a Kruskal--Wallis test across the five raters. PathOPEN's raters "
        r"differ far less than filtered PathVQA's, and on Benchmark 3 they are "
        r"statistically indistinguishable. Note that PathOPEN's narrow spread is partly "
        r"a ceiling effect: when 90--99\% of scores are the maximum there is little room "
        r"to disagree.}",
        r"\label{tab:per-evaluator}",
        r"\begin{tabular}{l l S[table-format=4.0]"
        r" S[table-format=1.3] S[table-format=1.3] S[table-format=1.3]"
        r" S[table-format=1.3] S[table-format=1.3]"
        r" S[table-format=1.2] c}",
        r"\toprule",
        r"Dataset & Criterion & {$n$} & \multicolumn{5}{c}{Pathologist mean score}"
        r" & {Spread} & {$P$} \\",
        r"\cmidrule(lr){4-8}",
        r" & & & {P1} & {P2} & {P3} & {P4} & {P5} & & \\",
        r"\midrule",
    ]

    display = {"PathOPEN": "PathOPEN", "Filtered_PathVQA": "filtered PathVQA"}
    for source in ("PathOPEN", "Filtered_PathVQA"):
        for benchmark, criterion, _, label in PILLAR1_ROWS:
            rows = subset[(subset.dataset == source)
                          & (subset.benchmark == benchmark)
                          & (subset.criterion == criterion)].sort_values("evaluator")
            if rows.empty:
                continue
            test = homogeneity[(homogeneity.dataset == source)
                               & (homogeneity.benchmark == benchmark)
                               & (homogeneity.criterion == criterion)]
            p_value = test.kruskal_p.iloc[0] if not test.empty else float("nan")
            p_text = (r"\textbf{n.s.}" if p_value >= 0.05
                      else (r"$<$0.001" if p_value < 0.001 else f"{p_value:.3f}"))
            means = " & ".join(f"{v:.3f}" for v in rows["mean"])
            spread = rows["mean"].max() - rows["mean"].min()
            lines.append(f"{display[source]} & {label} & {int(rows.n.sum())} & {means}"
                         f" & {spread:.2f} & {p_text} \\\\")
        if source == "PathOPEN":
            lines.append(r"\midrule")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def table_s2_defect_mechanism() -> str:
    """Supplementary: per-rater unscorable rates.

    Stronger than the mean-score comparison, because raters disagreeing about whether an
    item can be evaluated AT ALL is a more fundamental defect than disagreeing about its
    quality."""
    scores, _, _ = _load()
    subset = scores[scores.dataset.isin(["PathOPEN", "Filtered_PathVQA"])
                    & scores.benchmark.isin([1, 3])]

    lines = [
        r"% Generated by tables/make_tables.py - do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{\textbf{Per-pathologist rate of unscorable items.} Percentage of items "
        r"each pathologist scored $-1$ (``unable to comprehend the question and/or image, "
        r"or unable to make the evaluation''). On PathOPEN four of the five raters marked "
        r"\emph{no} item unscorable on any criterion, and the widest disagreement between "
        r"raters is 3.6 percentage points. On filtered PathVQA the same five raters "
        r"disagree by up to 70 points about whether items can be evaluated at all -- on "
        r"Benchmark 3 one pathologist found every item scorable while another rejected "
        r"70\% of theirs. Disagreement about answerability is a more fundamental defect "
        r"than disagreement about quality, because it means the item does not present a "
        r"well-posed question.}",
        r"\label{tab:defect-mechanism}",
        r"\begin{tabular}{l l S[table-format=2.1] S[table-format=2.1] S[table-format=2.1]"
        r" S[table-format=2.1] S[table-format=2.1] S[table-format=2.1] S[table-format=3.0]}",
        r"\toprule",
        r"Dataset & Criterion & \multicolumn{5}{c}{\% items scored $-1$, per pathologist}"
        r" & {Range} & {Pooled} \\",
        r"\cmidrule(lr){3-7}",
        r" & & {P1} & {P2} & {P3} & {P4} & {P5} & & {$n_{-1}$} \\",
        r"\midrule",
    ]

    display = {"PathOPEN": "PathOPEN", "Filtered_PathVQA": "filtered PathVQA"}
    for source in ("PathOPEN", "Filtered_PathVQA"):
        for benchmark, criterion, _, label in PILLAR1_ROWS:
            rows = subset[(subset.dataset == source)
                          & (subset.benchmark == benchmark)
                          & (subset.criterion == criterion)].sort_values("evaluator")
            if rows.empty:
                continue
            rates = " & ".join(f"{v:.1f}" for v in rows["pct_-1"])
            spread = rows["pct_-1"].max() - rows["pct_-1"].min()
            total = int(rows["n_-1"].sum())
            lines.append(f"{display[source]} & {label} & {rates} & {spread:.1f}"
                         f" & {total} \\\\")
        if source == "PathOPEN":
            lines.append(r"\midrule")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", dest="echo", action="store_true")
    args = parser.parse_args()

    outputs = {
        "table1_dataset_quality.tex": table1_dataset_quality(),
        "tableS1_per_evaluator.tex": table_s1_per_evaluator(),
        "tableS2_defect_mechanism.tex": table_s2_defect_mechanism(),
    }
    os.makedirs(TABLE_DIR, exist_ok=True)
    for name, content in outputs.items():
        path = os.path.join(TABLE_DIR, name)
        with open(path, "w") as f:
            f.write(content)
        print(f"wrote {name} ({len(content.splitlines())} lines)")
        if args.echo:
            print(content)


if __name__ == "__main__":
    main()
